server.port: 8083
spring.application.name: taxpayer-service
app.security.audience: ${KEYCLOAK_AUDIENCE:tax-api}
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}
spring.jpa.hibernate.ddl-auto: update
