spring.config.import: "optional:file:../.env[.properties],optional:file:.env[.properties]"
spring.jpa.hibernate.ddl-auto: update
spring.data.redis.ssl.enabled: false
eureka.instance.hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
